import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

export default function Home() {
    return (
        <>
            <Head>
                <title>FitList</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={`${styles['home-content']}`}>
                <section className={`${styles['transition-logo']}`}>
                    <h1 className={`${styles['logo']}`}>FitList</h1>
                </section>

                <section className={`${styles['home-page-content']}`}>
                    <h1 className={`${styles['logo']}`}>FitList</h1>

                    <p className={`${styles['home-page-content-p']}`}>FitList te ajuda a tornar o plano de exercícios mais dinâmicos, mais playlist!</p>
                </section>
            </div>
        </>

    )
}
